# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget
from PyQt5 import uic


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 60, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 110, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "点击我"))
        self.label.setText(_translate("Form", "简单文本"))


if __name__ == '__main__':
    myApp = QApplication(sys.argv)

    # 方法一：使用PyUIC5工具将ui文件转为代码
    # # myWin = QMainWindow()
    # myWin = QWidget()
    # myUI = Ui_Form()
    # myUI.setupUi(myWin)
    # myWin.show()
    # sys.exit(myApp.exec_())

    # 方法二：直接动态加载ui文件，不使用PyUIC5工具将ui文件转为代码
    ui = uic.loadUi("Thread_test.ui")
    ui.show()

    myApp.exec()