# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['D:\\pythonProject\\PyQt\\微软文字转语音.py'],
    pathex=[],
    binaries=[('D:\\pythonProject\\PyQt\\venv\\Scripts\\edge-tts.exe','.'),
		('D:\\pythonProject\\PyQt\\venv\\Scripts\\edge-playback.exe','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_playback','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_tts','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiohttp','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiohttp-3.8.4.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiosignal','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiosignal-1.3.1.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\async_timeout','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\async_timeout-4.0.2.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attrs','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attrs-22.2.0.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attr','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\frozenlist','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\frozenlist-1.3.3.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\multidict','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\multidict-6.0.4.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\yarl','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\yarl-1.8.2.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\myapp','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\myapp-0.1.dev0.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_tts-6.1.3.dist-info','.'),],
    datas=[('D:\\pythonProject\\PyQt\\venv\\Scripts\\edge-tts.exe','.'),
		('D:\\pythonProject\\PyQt\\venv\\Scripts\\edge-playback.exe','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_playback','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_tts','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiohttp','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiohttp-3.8.4.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiosignal','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\aiosignal-1.3.1.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\async_timeout','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\async_timeout-4.0.2.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attrs','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attrs-22.2.0.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\attr','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\frozenlist','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\frozenlist-1.3.3.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\multidict','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\multidict-6.0.4.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\yarl','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\yarl-1.8.2.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\myapp','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\myapp-0.1.dev0.dist-info','.'),
		('D:\\pythonProject\\PyQt\\venv\\Lib\\site-packages\\edge_tts-6.1.3.dist-info','.'),],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='微软文字转语音',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
