# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photoView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1229, 820)
        self.label_dis = QtWidgets.QLabel(Form)
        self.label_dis.setGeometry(QtCore.QRect(10, 10, 1211, 751))
        self.label_dis.setObjectName("label_dis")
        self.pushButton_up = QtWidgets.QPushButton(Form)
        self.pushButton_up.setGeometry(QtCore.QRect(490, 780, 75, 23))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(Form)
        self.pushButton_down.setGeometry(QtCore.QRect(590, 780, 75, 23))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_filePath = QtWidgets.QPushButton(Form)
        self.pushButton_filePath.setGeometry(QtCore.QRect(10, 780, 75, 23))
        self.pushButton_filePath.setObjectName("pushButton_filePath")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 780, 371, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_dis.setText(_translate("Form", "TextLabel"))
        self.pushButton_up.setText(_translate("Form", "上一张"))
        self.pushButton_down.setText(_translate("Form", "下一张"))
        self.pushButton_filePath.setText(_translate("Form", "打开文件夹"))
        self.label.setText(_translate("Form", "TextLabel"))
