# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signal_slot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtWidgets, uic
from PyQt5.QtWidgets import QApplication


# class Ui_Form(object):
#     def setupUi(self, Form):
#         Form.setObjectName("Form")
#         Form.resize(400, 300)
#         self.dial = QtWidgets.QDial(Form)
#         self.dial.setGeometry(QtCore.QRect(140, 30, 91, 91))
#         self.dial.setWrapping(True)
#         self.dial.setNotchesVisible(True)
#         self.dial.setObjectName("dial")
#         self.spinBox = QtWidgets.QSpinBox(Form)
#         self.spinBox.setGeometry(QtCore.QRect(110, 180, 201, 22))
#         self.spinBox.setObjectName("spinBox")
#
#         self.retranslateUi(Form)
#         self.dial.valueChanged['int'].connect(self.spinBox.setValue)  # type: ignore
#         self.spinBox.valueChanged['int'].connect(self.dial.setValue)  # type: ignore
#         QtCore.QMetaObject.connectSlotsByName(Form)
#
#     def retranslateUi(self, Form):
#         _translate = QtCore.QCoreApplication.translate
#         Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == '__main__':
    app = QApplication(sys.argv)

    ui = uic.loadUi('signal_slot.ui')
    ui.show()

    app.exec()
